-- 05_create_product_tables.sql
USE banco_core;

CREATE TABLE IF NOT EXISTS prd_producto_bancario (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  codigo_producto VARCHAR(40) NOT NULL UNIQUE,
  nombre_producto VARCHAR(120) NOT NULL,
  categoria VARCHAR(30) NOT NULL,
  requiere_aprobacion TINYINT(1) NOT NULL DEFAULT 0,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_prd_categoria CHECK (categoria IN ('CUENTAS','PRESTAMOS','SERVICIOS'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
