export const ROLES = {
  ANALISTA: 'ANALISTA_INTERNO',
  ADMIN: 'ANALISTA_INTERNO',
  VENTANILLA: 'EMPLEADO_VENTANILLA',
  COMERCIAL: 'EMPLEADO_COMERCIAL',
  CLIENTE_PERSONA: 'CLIENTE_PERSONA',
  EMPRESA_ADMIN: 'CLIENTE_EMPRESA_ADMIN',
  EMPRESA_OPERATIVO: 'EMPLEADO_EMPRESA_OPERATIVO',
  SUPERVISOR_EMPRESA: 'SUPERVISOR_EMPRESA',
} as const

export const ALL_ROLES = [
  ROLES.ANALISTA,
  ROLES.VENTANILLA,
  ROLES.COMERCIAL,
  ROLES.CLIENTE_PERSONA,
  ROLES.EMPRESA_ADMIN,
  ROLES.EMPRESA_OPERATIVO,
  ROLES.SUPERVISOR_EMPRESA,
] as const

export const ROLE_LABELS: Record<string, string> = {
  ANALISTA_INTERNO: 'Analista Interno',
  EMPLEADO_VENTANILLA: 'Empleado de Ventanilla',
  EMPLEADO_COMERCIAL: 'Empleado Comercial',
  CLIENTE_PERSONA: 'Cliente Persona Natural',
  CLIENTE_EMPRESA_ADMIN: 'Administrador de Empresa',
  EMPLEADO_EMPRESA_OPERATIVO: 'Operativo de Empresa',
  SUPERVISOR_EMPRESA: 'Supervisor de Empresa',
}
