BEGIN;

-- 1) Roles_Sistema
CREATE TABLE IF NOT EXISTS public.Roles_Sistema (
  ID_Rol      SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Nombre_Rol  TEXT NOT NULL UNIQUE,   -- AK
  Descripcion TEXT
);

-- 2) Clientes (unificado)
CREATE TABLE IF NOT EXISTS public.Clientes (
  Numero_Identificacion   TEXT PRIMARY KEY,
  Tipo_Cliente            VARCHAR(1),     -- text(1) en el diagrama
  Correo_Electronico      TEXT,
  Numero_de_telefono      TEXT,
  Direccion               TEXT,
  Rol_Cliente             TEXT,
  Nombre_Completo         TEXT,
  Fecha_de_nacimiento     DATE,
  Razon_Social            TEXT,
  Representante_Legal     TEXT,           -- FK (self)
  ID_Usuario_Comercial    INTEGER         -- FK -> Usuarios_del_Sistema (se agrega luego por ciclo)
);

-- FK auto-referenciada: Clientes.Representante_Legal -> Clientes.Numero_Identificacion
ALTER TABLE public.Clientes
  ADD CONSTRAINT fk_clientes_representante_legal
  FOREIGN KEY (Representante_Legal)
  REFERENCES public.Clientes (Numero_Identificacion);

-- 3) Usuarios_del_Sistema
CREATE TABLE IF NOT EXISTS public.Usuarios_del_Sistema (
  ID_Usuario                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Numero_Identificacion_Cliente TEXT,               -- FK -> Clientes
  Nombre_Completo              TEXT,
  ID_Identificacion            TEXT NOT NULL UNIQUE, -- AK
  Correo_Electronico           TEXT,
  Telefono                     TEXT,
  Fecha_Nacimiento             DATE,
  Direccion                    TEXT,
  ID_Rol                       SMALLINT,            -- FK -> Roles_Sistema
  Estado_Usuario               TEXT
);

ALTER TABLE public.Usuarios_del_Sistema
  ADD CONSTRAINT fk_usuarios_cliente
  FOREIGN KEY (Numero_Identificacion_Cliente)
  REFERENCES public.Clientes (Numero_Identificacion);

ALTER TABLE public.Usuarios_del_Sistema
  ADD CONSTRAINT fk_usuarios_rol
  FOREIGN KEY (ID_Rol)
  REFERENCES public.Roles_Sistema (ID_Rol);

-- Ahora sí: FK Clientes.ID_Usuario_Comercial -> Usuarios_del_Sistema.ID_Usuario (por ciclo)
ALTER TABLE public.Clientes
  ADD CONSTRAINT fk_clientes_usuario_comercial
  FOREIGN KEY (ID_Usuario_Comercial)
  REFERENCES public.Usuarios_del_Sistema (ID_Usuario);

-- 4) Producto_Bancario
CREATE TABLE IF NOT EXISTS public.Producto_Bancario (
  Codigo_Producto      TEXT PRIMARY KEY,
  Nombre_Producto      TEXT,
  Categoria            TEXT,
  Requiere_Aprobacion  BOOLEAN
);

-- 5) Cuenta_Bancaria
CREATE TABLE IF NOT EXISTS public.Cuenta_Bancaria (
  Numero_Cuenta          TEXT PRIMARY KEY,
  Codigo_producto_cuenta TEXT,     -- FK -> Producto_Bancario
  Tipo_Cuenta            TEXT,
  ID_Titular             TEXT,     -- FK -> Clientes
  Saldo_Actual           NUMERIC,
  Moneda                 TEXT,
  Estado_Cuenta          TEXT,
  Fecha_Apertura         DATE
);

ALTER TABLE public.Cuenta_Bancaria
  ADD CONSTRAINT fk_cuenta_producto
  FOREIGN KEY (Codigo_producto_cuenta)
  REFERENCES public.Producto_Bancario (Codigo_Producto);

ALTER TABLE public.Cuenta_Bancaria
  ADD CONSTRAINT fk_cuenta_titular
  FOREIGN KEY (ID_Titular)
  REFERENCES public.Clientes (Numero_Identificacion);

-- 6) Prestamo
CREATE TABLE IF NOT EXISTS public.Prestamo (
  ID_Prestamo               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Codigo_producto_prestamo   TEXT,     -- FK -> Producto_Bancario
  Tipo_Prestamo             TEXT,
  ID_Cliente_Solicitante    TEXT,     -- FK -> Clientes
  Monto_Solicitado          NUMERIC,
  Monto_Aprobado            NUMERIC,
  Tasa_Interes              NUMERIC,
  Plazo_Meses               INTEGER,
  Estado_Prestamo           TEXT,
  Fecha_Aprobacion          DATE,
  Fecha_Desembolso          DATE,
  Cuenta_Destino_Desembolso TEXT      -- FK -> Cuenta_Bancaria
);

ALTER TABLE public.Prestamo
  ADD CONSTRAINT fk_prestamo_producto
  FOREIGN KEY (Codigo_producto_prestamo)
  REFERENCES public.Producto_Bancario (Codigo_Producto);

ALTER TABLE public.Prestamo
  ADD CONSTRAINT fk_prestamo_cliente
  FOREIGN KEY (ID_Cliente_Solicitante)
  REFERENCES public.Clientes (Numero_Identificacion);

ALTER TABLE public.Prestamo
  ADD CONSTRAINT fk_prestamo_cuenta_desembolso
  FOREIGN KEY (Cuenta_Destino_Desembolso)
  REFERENCES public.Cuenta_Bancaria (Numero_Cuenta);

-- 7) Transferencia
CREATE TABLE IF NOT EXISTS public.Transferencia (
  ID_Transferencia     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Tipo_Transferencia   TEXT,
  Cuenta_Origen        TEXT,       -- FK -> Cuenta_Bancaria
  Monto_Total          NUMERIC,
  Fecha_Creacion       TIMESTAMP,
  Fecha_Aprobacion     TIMESTAMP,
  Estado_Transferencia TEXT,
  ID_Usuario_Creador   INTEGER,    -- FK -> Usuarios_del_Sistema
  ID_Usuario_Aprobador INTEGER     -- FK -> Usuarios_del_Sistema
);

ALTER TABLE public.Transferencia
  ADD CONSTRAINT fk_transferencia_origen
  FOREIGN KEY (Cuenta_Origen)
  REFERENCES public.Cuenta_Bancaria (Numero_Cuenta);

ALTER TABLE public.Transferencia
  ADD CONSTRAINT fk_transferencia_usuario_creador
  FOREIGN KEY (ID_Usuario_Creador)
  REFERENCES public.Usuarios_del_Sistema (ID_Usuario);

ALTER TABLE public.Transferencia
  ADD CONSTRAINT fk_transferencia_usuario_aprobador
  FOREIGN KEY (ID_Usuario_Aprobador)
  REFERENCES public.Usuarios_del_Sistema (ID_Usuario);

-- 8) Transferencia_Detalle
CREATE TABLE IF NOT EXISTS public.Transferencia_Detalle (
  ID_Transferencia INTEGER,  -- PK, FK -> Transferencia
  No_Item          INTEGER,  -- PK
  Cuenta_Destino   TEXT,     -- FK -> Cuenta_Bancaria
  Monto            NUMERIC,
  Concepto         TEXT,
  PRIMARY KEY (ID_Transferencia, No_Item)
);

ALTER TABLE public.Transferencia_Detalle
  ADD CONSTRAINT fk_transf_detalle_transferencia
  FOREIGN KEY (ID_Transferencia)
  REFERENCES public.Transferencia (ID_Transferencia);

ALTER TABLE public.Transferencia_Detalle
  ADD CONSTRAINT fk_transf_detalle_destino
  FOREIGN KEY (Cuenta_Destino)
  REFERENCES public.Cuenta_Bancaria (Numero_Cuenta);

-- 9) Bitacora_de_Operaciones
CREATE TABLE IF NOT EXISTS public.Bitacora_de_Operaciones (
  ID_Bitacora          TEXT PRIMARY KEY,
  Tipo_Operacion       TEXT,
  Fecha_Hora_Operacion TIMESTAMP,
  ID_Usuario           INTEGER,   -- FK -> Usuarios_del_Sistema
  Rol_Usuario          TEXT,
  ID_Producto_Afectado TEXT,
  Datos_Detalle        JSONB
);

ALTER TABLE public.Bitacora_de_Operaciones
  ADD CONSTRAINT fk_bitacora_usuario
  FOREIGN KEY (ID_Usuario)
  REFERENCES public.Usuarios_del_Sistema (ID_Usuario);

COMMIT;